name: Create and Push Docker Image

on:
  push:
    branches:
      - main
  workflow_dispatch: # Permet de déclencher manuellement le workflow

jobs:
  build_and_push_image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Docker Login
        uses: docker/login-action@v3.3.0
        with:
          username: "florian5629"
          password: "dckr_pat_4FB8k8CjsSHrLP_s6Z1Wrexfpbw" # Assurez-vous que ce secret est défini dans vos paramètres GitHub

      - name: Build Docker image
        run: |
          docker build -t florian5629/poire .

      - name: Push Docker image to Docker Hub
        run: |
          docker push florian5629/poire
