name: Create and Push Docker Image

on:
  push:
    branches:
      - main
  workflow_dispatch: # Permet de déclencher manuellement le workflow

jobs:
  create_dockerfile:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Recreate Dockerfile
        run: |
          rm -f Dockerfile
          echo "FROM node:20-alpine" > Dockerfile
          echo "WORKDIR /greg" >> Dockerfile
          echo "COPY . ." >> Dockerfile
          echo "RUN yarn install" >> Dockerfile
          echo 'CMD ["node", "src/index.js"]' >> Dockerfile
          echo "EXPOSE 3000" >> Dockerfile

      - name: Commit Dockerfile if changed
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git add Dockerfile
          if ! git diff --cached --quiet; then
            git commit -m "Update Dockerfile created by GitHub Action"
            git push
          else
            echo "No changes to commit"
          fi

  build_and_push_image:
    needs: create_dockerfile
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log in to GitHub Container Registry
        run: echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build Docker image
        run: |
          IMAGE_NAME="ghcr.io/d3ltarak/d3ltarak/getting-started-app:latest"
          docker build -t $IMAGE_NAME .

      - name: Push Docker image
        run: |
          IMAGE_NAME="ghcr.io/d3ltarak/d3ltarak/getting-started-app:latest"
          docker push $IMAGE_NAME 
